# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfaff5045c098e928542b720bd89a5d25dd2f44c3fecaccc7f375badd2126c740be813b2bc1ee8fb693c921a4c4ffb51a2c2a2fa200244010a67b7ac8aed1095

test:
  secret_key_base: 2b69ee535f4ef9929ba9f7d73f554b88e9af712425540a35204c03293e9ab3ffc68d62e393f336664a8a413751fadac30ba66b3719575cac92a20c080553cd9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
